/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import {StudentDtoToReturnSmall} from "../../models/student-dto-to-small-return";


export interface GetAllStudents1$Params {
  name: string;
}

export function getAllStudents1(http: HttpClient, rootUrl: string, params: GetAllStudents1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StudentDtoToReturnSmall>>> {
  const rb = new RequestBuilder(rootUrl, getAllStudents1.PATH, 'get');
  if (params) {
    rb.path('name', params.name, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StudentDtoToReturnSmall>>;
    })
  );
}

getAllStudents1.PATH = '/schoolYear/{name}/students';
