/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetAllSchoolYearsByDepartment$Params {
  department: 'BackendDevelopemet' | 'FullStackDevelopement' | 'FrontDevelopement' | 'AI_MachineLearning';
}

export function getAllSchoolYearsByDepartment(http: HttpClient, rootUrl: string, params: GetAllSchoolYearsByDepartment$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
  const rb = new RequestBuilder(rootUrl, getAllSchoolYearsByDepartment.PATH, 'get');
  if (params) {
    rb.path('department', params.department, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<string>>;
    })
  );
}

getAllSchoolYearsByDepartment.PATH = '/infos/schoolYear/Department/{department}';
