/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthentificationDto {
  granType?: string;
  password?: string;
  refreshToken?: string;
  userName?: string;
  withRefreshToken?: boolean;
}
