/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HistoryToSend {
  date: number;
  state: 'Succeed' | 'Failed' | 'In_Progress';
  studentEmail: string;
}
