/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HistoryToReturn {
  date?: number;
  schoolYearName?: string;
  state?: 'Succeed' | 'Failed' | 'In_Progress';
  type?: 'Bachelor' | 'Master' | 'Engineer';
}
