/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Image {
  createdAt?: string;
  id?: number;
  imageName?: string;
  imagePath?: string;
  imageType?: string;
  size?: number;
  updatedAt?: string;
}
