/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NoteToSend {
  comment?: string;
  coursName?: string;
  idStudent?: number;
  idProf?: number;
  value?: number;
}
