/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Pdf {
  createdAt?: string;
  id?: number;
  pdfName: string;
  pdfPath?: string;
  pdfType?: string;
  size?: number;
  updatedAt?: string;
}
