/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProfessorToReturnSmall {
  id:number,
  email: string;
  fullName?: string;
  imageName?:string;


}
