/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RequestToSend {
  projectName?: string;
  purpose?: string;
  title?: string;
  userId?: number;
}
