/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RequestToChange {
  idOwner?: number;
  idUser?: number;
  projectName?: string;
  state?: 'Pending' | 'Accepted' | 'Canceled';
}
