/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SchoolYearToReturn {
  departement?: 'BackendDevelopemet' | 'FullStackDevelopement' | 'FrontDevelopement' | 'AI_MachineLearning';
  maxCours?: number;
  maxStudents?: number;
  name?: string;
  type?: 'Bachelor' | 'Master' | 'Engineer';
}
