/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Video {
  createdAt?: string;
  id?: number;
  size?: number;
  updatedAt?: string;
  videoName?: string;
  videoPath?: string;
  videoType?: string;
}
