/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudentDtoToReturn } from '../../models/student-dto-to-return';

export interface GetStudentByEmail$Params {
  email?: string;
}

export function getStudentByEmail(http: HttpClient, rootUrl: string, params: GetStudentByEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentDtoToReturn>> {
  const rb = new RequestBuilder(rootUrl, getStudentByEmail.PATH, 'get');
  if (params) {
    rb.path('email', params.email, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentDtoToReturn>;
    })
  );
}

getStudentByEmail.PATH = '/students/email/{email}';
