/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudentDtoToReturn } from '../../models/student-dto-to-return';
import {StudentDtoToReturnSmall} from "../../models/student-dto-to-small-return";
import {GetStudentByEmail$Params} from "./get-student-by-email";



export function getStudentByEmailSmall(http: HttpClient, rootUrl: string, params: GetStudentByEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentDtoToReturnSmall>> {
  const rb = new RequestBuilder(rootUrl, getStudentByEmailSmall.PATH, 'get');
  if (params) {
    rb.path('email', params.email, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentDtoToReturnSmall>;
    })
  );
}

getStudentByEmailSmall.PATH = '/students/necessary/email/{email}';
