/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NoteToReturn } from '../../models/note-to-return';

export interface GetAllNotes$Params {
  email: string;
}

export function getAllNotes(http: HttpClient, rootUrl: string, params: GetAllNotes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NoteToReturn>>> {
  const rb = new RequestBuilder(rootUrl, getAllNotes.PATH, 'get');
  if (params) {
    rb.path('email', params.email, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<NoteToReturn>>;
    })
  );
}

getAllNotes.PATH = '/students/{email}/notes';
