/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import {Observable, timeout} from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectToReturnTotal } from '../../models/ProjectToReturnTotal';

export interface GetAllInformations$Params {
  name: string;
}

export function getAllInformations(http: HttpClient, rootUrl: string, params: GetAllInformations$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectToReturnTotal>> {
  const rb = new RequestBuilder(rootUrl, getAllInformations.PATH, 'get',);
  if (params) {
    rb.path('name', params.name, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectToReturnTotal>;
    })
  );
}

getAllInformations.PATH = '/project/info/{name}';
