/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudentDtoToReturn } from '../../models/student-dto-to-return';
import {ProjectToReturn} from "../../models/ProjectToReturn";

export interface GetAllProjects$Params {
}

export function getAllProjects(http: HttpClient, rootUrl: string, params?: GetAllProjects$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProjectToReturn>>> {
  const rb = new RequestBuilder(rootUrl, getAllProjects.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProjectToReturn>>;
    })
  );
}

getAllProjects.PATH = '/projects';
