/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AdminToSend } from './models/admin-to-send';
export { AuthentificationDto } from './models/authentification-dto';
export { CoursToReturn } from './models/cours-to-return';
export { CoursToSend } from './models/cours-to-send';
export { CourToSchoolYearDto } from './models/cour-to-school-year-dto';
export { EvaluationToReturn } from './models/evaluation-to-return';
export { EvaluationToSend } from './models/evaluation-to-send';
export { HistoryToReturn } from './models/history-to-return';
export { HistoryToSend } from './models/history-to-send';
export { NoteToReturn } from './models/note-to-return';
export { NoteToSend } from './models/note-to-send';
export { ProfessorToReturn } from './models/professor-to-return';
export { ProfessorToSend } from './models/professor-to-send';
export { ProjectToSend } from './models/project-to-send';
export { RequestToChange } from './models/request-to-change';
export { RequestToSend } from './models/request-to-send';
export { SchoolYearToReturn } from './models/school-year-to-return';
export { StudentDtoToReturn } from './models/student-dto-to-return';
export { StudentDtoToSend } from './models/student-dto-to-send';
export { Tokens } from './models/tokens';
