/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { SchoolYearControllerService } from './services/school-year-controller.service';
export { RequestControllerService } from './services/request-controller.service';
export { ProjectControllerService } from './services/project-controller.service';
export { ProfessorControllerService } from './services/professor-controller.service';
export { EvaluationControllerService } from './services/evaluation-controller.service';
export { CourControllerService } from './services/cour-controller.service';
export { AuthenticationControllerService } from './services/authentication-controller.service';
export { AdministratorControllerService } from './services/administrator-controller.service';
export { StudentControllerService } from './services/student-controller.service';
