/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


import {ProfessorToReturn} from "../../models/professor-to-return";



export interface GetProfessorByID$Params {
  id?: number;
}

export function getProfessorAllInfosByID(http: HttpClient, rootUrl: string, params: GetProfessorByID$Params, context?: HttpContext): Observable<StrictHttpResponse<ProfessorToReturn>> {
  const rb = new RequestBuilder(rootUrl, getProfessorAllInfosByID.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProfessorToReturn>;
    })
  );
}

getProfessorAllInfosByID.PATH = '/professor/{id}';
