/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProfessorToReturn } from '../../models/professor-to-return';

export interface GetAllProfessors1$Params {
}

export function getAllProfessors1(http: HttpClient, rootUrl: string, params?: GetAllProfessors1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProfessorToReturn>>> {
  const rb = new RequestBuilder(rootUrl, getAllProfessors1.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProfessorToReturn>>;
    })
  );
}

getAllProfessors1.PATH = '/professors';
