/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import {ProfessorToReturnSmall} from "../../models/professor-to-return-small";


export interface GetProfessorByEmail$Params {
  email?: string;
}



export function getProfessorByEmailSmall(http: HttpClient, rootUrl: string, params: GetProfessorByEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<ProfessorToReturnSmall>> {
  const rb = new RequestBuilder(rootUrl, getProfessorByEmailSmall.PATH, 'get');
  if (params) {
    rb.path('email', params.email, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProfessorToReturnSmall>;
    })
  );
}

getProfessorByEmailSmall.PATH = '/professor/necessary/email/{email}';
