/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CoursToReturn } from '../../models/cours-to-return';
import {SchoolYearAndCoursesReturn} from "../../models/school-year-and-courses-return";

export interface GetAllCourses$Params {
  id: number;
}

export function getAllCourses(http: HttpClient, rootUrl: string, params: GetAllCourses$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SchoolYearAndCoursesReturn>>> {
  const rb = new RequestBuilder(rootUrl, getAllCourses.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SchoolYearAndCoursesReturn>>;
    })
  );
}

getAllCourses.PATH = '/professor/{id}/courses';
