/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import {GetProfessor$Params} from "../cour-controller/get-professor";
import {ProfessorToReturn} from "../../models/professor-to-return";
import {GetProfessorByEmail$Params} from "./get-professor-by-email-small";



export function getProfessorAllInfosByEmail(http: HttpClient, rootUrl: string, params: GetProfessorByEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<ProfessorToReturn>> {
  const rb = new RequestBuilder(rootUrl, getProfessorAllInfosByEmail.PATH, 'get');
  if (params) {
    rb.path('email', params.email, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProfessorToReturn>;
    })
  );
}

getProfessorAllInfosByEmail.PATH = '/professor/email/{email}';
