/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RequestToSend } from '../../models/request-to-send';
import {RequestToReturn} from "../../models/request-to-return";

export interface AddRequest$Params {
      body: RequestToSend
}

export function addRequest(http: HttpClient, rootUrl: string, params: AddRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<RequestToReturn>> {
  const rb = new RequestBuilder(rootUrl, addRequest.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RequestToReturn>;
    })
  );
}

addRequest.PATH = '/request';
