/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RequestToChange } from '../../models/request-to-change';
import {RequestToReturn} from "../../models/request-to-return";

export interface ChangeState$Params {
      body: RequestToChange
}

export function changeState(http: HttpClient, rootUrl: string, params: ChangeState$Params, context?: HttpContext): Observable<StrictHttpResponse<RequestToReturn>> {
  const rb = new RequestBuilder(rootUrl, changeState.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RequestToReturn>;
    })
  );
}

changeState.PATH = '/request/state';
